name: Terraform Apply

on: [workflow_dispatch]

defaults:
  run:
    working-directory: ./Testlab

jobs:
  terraform:
    runs-on: ubuntu-latest

      steps:
      - uses: azure/login@v1
      with:
        creds: ${{ secrets.ARM_AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        
      - name: Terraform Apply
        run: terraform apply --auto-approve
